apiVersion: v1
kind: Service
metadata:
  name: nginx-ranjeet-nodeport
  namespace: nginx-demo
  labels:
    app: nginx-ranjeet
spec:
  type: NodePort
  selector:
    app: nginx-ranjeet
  ports:
    - name: http
      port: 80
      targetPort: 80
      nodePort: 30080

